name: zeus_app_premium
description: ZEUS Premium Banking App
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Receipts: generate, print/share, and save safely
  pdf: ^3.11.0
  printing: ^5.11.0
  path_provider: ^2.1.4

  # For Splash → Home/KYC handoff flag
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/zeus_logo.png
