name: zeus_app_premium
description: ZEUS Premium Banking & Wallet App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.2.1
  local_auth: ^2.2.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/zeus_logo.png
