name: zeus_premium
description: ZEUS Premium Banking – Android, iOS, Web
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI helpers
  intl: ^0.19.0

  # PDF generation and web/mobile sharing
  pdf: ^3.10.8
  printing: ^5.13.0
  share_plus: ^10.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/zeus_logo.png
