name: zeus_app_premium
description: ZEUS Premium – clean, clickable demo with receipts, bottom nav, splash.
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  collection: ^1.18.0

  # PDF receipt + printing (works on web with Flutter 3.22+)
  pdf: ^3.11.0
  printing: ^5.13.1

  # Share & file save (web-friendly)
  share_plus: ^10.0.2
  file_saver: ^0.2.13
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/zeus_logo.png
