name: ZEUS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_NAME: zeus_app_premium
  FLUTTER_VERSION: "3.27.0"
  JAVA_VERSION: "17"

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter create . --platforms web   # ensure web platform enabled
      - run: flutter build web --release --base-href="/${{ env.REPO_NAME }}/"
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - run: flutter pub get
      - run: flutter create . --platforms android   # ensure android scaffold exists
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 14

  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter create . --platforms ios   # ensure ios scaffold exists
      - run: flutter build ios --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
