  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Clean Gradle & Flutter cache
        run: |
          flutter clean
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches/
          rm -rf ~/.pub-cache

      - name: Recreate Android scaffold (safe overwrite)
        run: |
          cp -r lib lib_backup 2>/dev/null || true
          flutter create . --platforms=android --overwrite
          git restore --source=HEAD -- lib || true
          [ -d lib_backup ] && cp -rn lib_backup/* lib/ 2>/dev/null || true
          rm -rf lib_backup
          chmod +x android/gradlew || true

      - name: Pub get
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug --stacktrace --verbose

      - name: Upload APK artifact (14 days)
        uses: actions/upload-artifact@v4
        with:
          name: zeus_app_premium-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 14
