name: ZEUS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
      - run: flutter pub get
      - run: flutter create . --platforms web
      - run: flutter build web --release --base-href="/zeus_app_premium/"
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
      - run: flutter pub get
      - run: flutter create . --platforms android
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
      - run: flutter pub get
      - run: flutter create . --platforms ios
      - run: flutter build ios --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
