name: ZEUS CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Ensure platforms exist (web)
        run: |
          if [ ! -d "web" ]; then
            flutter create . --platforms web
          fi

      - name: Pub get
        run: flutter pub get

      - name: Build Web (GitHub Pages base href)
        run: flutter build web --release --base-href="/zeus_app_premium/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17 (AGP requirement)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Ensure platforms exist (android)
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms android
          fi

      - name: Pub get
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact (14 days)
        uses: actions/upload-artifact@v4
        with:
          name: ZEUS-APK-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 14

  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Ensure platforms exist (ios)
        run: |
          if [ ! -d "ios" ]; then
            flutter create . --platforms ios
          fi

      - name: Pub get
        run: flutter pub get

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign

  deploy:
    needs: [web-build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
